[topics]
raw_db = pdf
an_db = pdf-analysis


# This section defines all the files path required for stitching and calibration
[PATH]
user_data = /nsls2/data/pdf/pdfhack/legacy/processed/xpdacq_data/user_data
tiff_base = tiff_base
# tiff_base = tiff_base/test
config_base = config_base
pdfgetx = pdfgetx
# pilatus_PDF, pilatus_XRD have to be put in ~/config_base
pilatus_PDF = pilatus_PDF
pilatus_XRD = pilatus_XRD
pe1c_PDF = pe1c_PDF
pe1c_XRD = pe1c_XRD
pe2c_SAXS = pe2c_SAXS
# Masks and poin have to be put in ~/config_base/pilatus_PDF or ~/config_base/pilatus_XRD
mask_01 = Mask_pos1_ext_BS.npy
mask_02 = Mask_pos2_ext_BS.npy
mask_03 = Mask_pos3_ext_BS.npy
stitched_mask = Mask_stitched.npy
# stitched_mask = Mask_pos3_ext_BS.npy
merged_poin = merged.poni
# merged_poin = xpdAcq_calib_info.poni
mask_pe1c = Mask.npy
poni_pe1c = xpdAcq_calib_info.poni
mask_pe2c = Mask.npy
poni_pe2c = xpdAcq_calib_info.poni
# flat_filed has to be put in ~/config_base
flat_filed = flat_field
# flat_filed tiff have to be put in ~/config_base/flat_filed
flat_field_pila = flat_filed_pila.tiff
flat_field_pe1c = flat_filed_pe1c.tiff
flat_field_pe2c = flat_filed_pe2c.tiff



[SUM]
osetx = 27
osety = 27
use_flat_field_pila = False
use_flat_field_pe1c = False
use_flat_field_pe2c = False
num_positions = 3
detector_Xmotor = Grid_X
detector_Ymotor = Grid_Y
pixel_size = 0.172 ## mm



[INTEGRATION]
# npt_rad is equivalent to binning
npt_rad = 4096
npt_azim = 720
polarization = 0.99
UNIT = q_A^-1
low_limit_pcfilter = 2
up_limit_pcfilter = 98



[pdfgetx3]
do_reduction = True
use_auto_bkg = True
# backgroundfile = /nsls2/data/pdf/pdfhack/legacy/processed/xpdacq_data/user_data/tiff_base/23_carbon_PVDF_CP/pe1/23_carbon_PVDF_CP_20260209-144517_2e18ed_sub.iq
backgroundfile =
# rpoly = 0.85
rpoly = 0.7
qmaxinst = 25
qmin = 0.6
qmax = 25
rmin = 0.0
rmax = 100.0
rstep = 0.01
dataformat = QA
outputtype = sq, fq, gr
## Plot the specified results and activate interactive mode.
## A comma separated list with items such as "iq", "sq", "fq", "gr".
## No plot is produced when empty, "none" or "NONE".
plot = none
# file_prefix = {start[sample_name]}_{start[readable_time]}_{start[original_run_uid]:6.6}_



[TEMPERATURE]
# Select one of the tem_controler below and comment others
temp_controller = None
# temp_controller = cryostat_A
# temp_controller = hotairblower
# temp_controller = linkam_T96
# temp_controller = cryostream_T
# temp_controller = eurotherm3504
# temp_controller = thermocouple_c