[workspace]
channels = ["conda-forge"]
name = "pdf-auto"
platforms = ["linux-64"]
version = "2026-1.0"

[system-requirements]
libc = "2.17"

[dependencies]
python = ">=3.12,<3.13"
bluesky-base = "==1.15.0"
event-model = "*"
ipython = ">=9.5"
matplotlib-base = ">=3.10,<4"
numpy = ">2"
pandas = ">=3.0,<4"
pyside6 = "*"
pyfai = "==2025.3.0"
scipy = ">=1.17,<2"
tifffile = "*"
tiled-client = ">=0.2.3,<0.3"

[pypi-dependencies]
"diffpy.pdfgetx" = { path = "/home/xf28id1/Documents/pdfgetx-2.4.0-wheels/diffpy_pdfgetx-2.4.0-cp312-cp312-linux_x86_64.whl" }
pdfstream = { git = "https://github.com/NSLS-II-PDF/pdfstream.git", rev = "v0.5.x" }

[tasks]
pdf-analysis = { cmd = "python -m pdf_auto pdf", env = { PYTHONPATH = "/home/xf28id1/src/pdf-auto/src", MPLBACKEND = "qtagg" } }
pdf-save = { cmd = "python -m pdf_auto save", env = { PYTHONPATH = "/home/xf28id1/src/pdf-auto/src", MPLBACKEND = "qtagg" } }
pdf-plot = { cmd = "python -m pdf_auto plot", env = { PYTHONPATH = "/home/xf28id1/src/pdf-auto/src", MPLBACKEND = "qtagg" } }
